
extends: eslint:recommended
env:
  node: true
  es6: true

parserOptions:
  sourceType: module
  ecmaVersion: latest

rules:
  quotes: [warn, single]
  semi: [warn, never]
  require-await: error
  keyword-spacing:
    - warn
    - overrides:
        if: { after: false }
        for: { after: false }
        while: { after: false }
        switch: { after: false }
